
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - node_modules_data:/app/node_modules

    env_file:
      - ./backend/.env
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules_data:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  mongo_data:
  node_modules_data:
  


